# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_8FjghLBrgRq5CUGAv4t1ckBcQa5lta
"""

def encryption(text, password):
    """Encrypts the given text using a simple substitution cipher."""
    encrypted_text = ""
    for char in text:
        encrypted_text += chr(ord(char) + len(password))  # Shifts ASCII value by the length of the password
    return encrypted_text

def decryption(encrypted_text, password):
    """Decrypts the given text encrypted with a simple substitution cipher."""
    decrypted_text = ""
    for char in encrypted_text:
        decrypted_text += chr(ord(char) - len(password))  # Shifts ASCII value back by the length of the password
    return decrypted_text

def main():
    print("Welcome to Simple Encryption and Decryption Program\n")

    text = input("Enter the text to encrypt: ")
    password = input("Enter a password (at least 8 characters): ")

    if len(password) < 8:
        print("Password should be at least 8 characters long.")
        return

    encrypted_text = encryption(text, password)
    print("\nEncrypted Text:", encrypted_text)

    decrypted_text = decryption(encrypted_text, password)
    print("Decrypted Text:", decrypted_text)